Feature: Different Operation for Item :: POST-PUT-PATCH-GET-DELETE

  Scenario: Get API for a Item which Exists and any Existing Items
    Given a data for item "11" is needed
    When the request to get the item is made
    Then a 200 response code is returned
    And a item with "id" as "11" is present
    And a item with "name" as "Apple iPad Mini 5th Gen" is present
    And a item with "data.Capacity" as "254 GB" is present
    And a item with "data.'Screen size'" as "7.9" is present

  Scenario: Verify an item creation failure Once Post API is Triggered with invalid request body
    When the request to add the item is made
    Then a 400 response code is returned
    And an error with text "400 Bad Request. If you are trying to create or update the data, potential issue is that you are sending incorrect body json or it is missing at all." is returned

  Scenario: Verify an item can be created Once Post API is Triggered
    Given a "Apple MacBook Pro 16" item is created
    And is a "Intel Core i9" CPU model
    And has a price of "1849.99"
    When the request to add the item is made
    Then a 200 response code is returned
    And a "Apple MacBook Pro 16" is created

  Scenario: Get API for a Item which Exists and Recently created
    Given a data for item "<NewlyCreatedItem>" is needed
    When the request to get the item is made
    Then a 200 response code is returned
    And a item with "id" as "<NewlyCreatedItem>" is present
    And a item with "name" as "Apple MacBook Pro 16" is present
    And a item with "data.price" as "1849.99" is present
    And a item with "data.cpuModel" as "Intel Core i9" is present

  Scenario: Get API for Set of Items in which all Items Exist
    Given a data for item "10,11,<NewlyCreatedItem>" is needed
    When the request to get list of the item is made
    Then a 200 response code is returned
    And the count of item is 3 in returned response

  Scenario: Get API for Set of Items in which some Items Exist
    Given a data for item "10,11,99" is needed
    When the request to get list of the item is made
    Then a 200 response code is returned
    And the count of item is 2 in returned response

  Scenario: Get API for Set of Items in which none items Exist
    Given a data for item "98,99" is needed
    When the request to get list of the item is made
    Then a 200 response code is returned
    And the count of item is 0 in returned response

  Scenario: Get API for All Items
    When the request to get list of the item is made
    Then a 200 response code is returned
    And a item with "id" as "11" is present in All Items

  Scenario: Patch API for a Item which does not exist
    Given a data for item "99" is needed
    And a "Apple MacBook Pro 16- Updated2" item is created
    When the request to update the item using "PATCH" is made
    Then a 404 response code is returned
    And an error with text "The Object with id = 99 doesn't exist. Please provide an object id which exists or generate a new Object using POST request and capture the id of it to use it as part of PATCH request after that." is returned

  Scenario: Put API for a Item which does not exist
    Given a data for item "99" is needed
    And a "Apple MacBook Pro 16- Updated1" item is created
    When the request to update the item using "PUT" is made
    Then a 404 response code is returned
    And an error with text "The Object with id = 99 doesn't exist. Please provide an object id which exists or generate a new Object using POST request and capture the id of it to use it as part of PUT request after that." is returned

  Scenario: Patch API for a Item which is Reserved and valid Request Body
    Given a data for item "11" is needed
    And a "Apple MacBook Pro 16- Updated2" item is created
    When the request to update the item using "PATCH" is made
    Then a 405 response code is returned
    And an error with text "11 is a reserved id and the data object of it cannot be overridden. You can create a new object via POST request and use new generated by id from it to send a PATCH request." is returned

  Scenario: Put API for a Item which is Reserved and valid Request Body
    Given a data for item "11" is needed
    And a "Apple MacBook Pro 16- Updated1" item is created
    When the request to update the item using "PUT" is made
    Then a 405 response code is returned
    And an error with text "11 is a reserved id and the data object of it cannot be overridden. You can create a new object via POST request and use new generated by id from it to send a PUT request." is returned

  Scenario: Patch API for a Item which Exists but Invalid Request Body
    Given a data for item "<NewlyCreatedItem>" is needed
    When the request to update the item using "PATCH" is made
    Then a 400 response code is returned
    And an error with text "400 Bad Request. If you are trying to create or update the data, potential issue is that you are sending incorrect body json or it is missing at all." is returned

  Scenario: Put API for a Item which Exists but Invalid Request Body
    Given a data for item "<NewlyCreatedItem>" is needed
    When the request to update the item using "PUT" is made
    Then a 400 response code is returned
    And an error with text "400 Bad Request. If you are trying to create or update the data, potential issue is that you are sending incorrect body json or it is missing at all." is returned

  Scenario: Patch API for a Item which is Recently Created and valid Request Body
    Given a data for item "<NewlyCreatedItem>" is needed
    And a "Apple MacBook Pro 16- Updated2" item is created
    When the request to update the item using "PATCH" is made
    Then a 200 response code is returned
    And a item with "id" as "<NewlyCreatedItem>" is present
    And a item with "name" as "Apple MacBook Pro 16- Updated2" is present
    And a item with "data.price" as "1849.99" is present
    And a item with "data.cpuModel" as "Intel Core i9" is present

  Scenario: Get API for a Item which recently updated using Patch
    Given a data for item "<NewlyCreatedItem>" is needed
    When the request to get the item is made
    Then a 200 response code is returned
    And a item with "id" as "<NewlyCreatedItem>" is present
    And a item with "name" as "Apple MacBook Pro 16- Updated2" is present
    And a item with "data.price" as "1849.99" is present
    And a item with "data.cpuModel" as "Intel Core i9" is present

  Scenario: Put API for a Item which is Recently Created and valid Request Body
    Given a data for item "<NewlyCreatedItem>" is needed
    And a "Apple MacBook Pro 16- Updated3" item is created
    And has a price of "1899.99"
    When the request to update the item using "PATCH" is made
    Then a 200 response code is returned
    And a item with "id" as "<NewlyCreatedItem>" is present
    And a item with "name" as "Apple MacBook Pro 16- Updated3" is present
    And a item with "data.price" as "1899.99" is present
    And a item with "data.cpuModel" as "null" is present

  Scenario: Get API for a Item which recently updated using Put
    Given a data for item "<NewlyCreatedItem>" is needed
    When the request to get the item is made
    Then a 200 response code is returned
    And a item with "id" as "<NewlyCreatedItem>" is present
    And a item with "name" as "Apple MacBook Pro 16- Updated3" is present
    And a item with "data.price" as "1899.99" is present
    And a item with "data.cpuModel" as "null" is present

  Scenario: Delete API for a Item which Exists
    Given a data for item "<NewlyCreatedItem>" is needed
    When the request to delete the item is made
    Then a 200 response code is returned
    And a message with text "Object with id = <NewlyCreatedItem> has been deleted." is returned

  Scenario: Get API for a Item which does not Exist
    Given a data for item "<NewlyCreatedItem>" is needed
    When the request to get the item is made
    Then a 404 response code is returned
    And an error with text "Oject with id=<NewlyCreatedItem> was not found." is returned

  Scenario: Delete API for a Item which does not Exist
    Given a data for item "<NewlyCreatedItem>" is needed
    When the request to delete the item is made
    Then a 404 response code is returned
    And an error with text "Object with id = <NewlyCreatedItem> doesn't exist." is returned

  Scenario: Delete API for a Item which is Reserved
    Given a data for item "11" is needed
    When the request to delete the item is made
    Then a 405 response code is returned
    And an error with text "11 is a reserved id and the data object of it cannot be deleted. You can create your own new object via POST request and try to send a DELETE request with new generated object id." is returned